blob_chunk:
  obis-biodiversity:
  - Hackathons/obis_chunk_0.parquet
  - Hackathons/obis_chunk_1.parquet
  - Hackathons/obis_chunk_10.parquet
  - Hackathons/obis_chunk_11.parquet
  - Hackathons/obis_chunk_12.parquet
  - Hackathons/obis_chunk_2.parquet
  - Hackathons/obis_chunk_3.parquet
  - Hackathons/obis_chunk_4.parquet
  - Hackathons/obis_chunk_5.parquet
  - Hackathons/obis_chunk_6.parquet
  - Hackathons/obis_chunk_7.parquet
  - Hackathons/obis_chunk_8.parquet
  - Hackathons/obis_chunk_9.parquet
  vestas:
  - vcl_ts_CN.csv
  - vcl_ts_NL.csv
  - vcl_ts_NO.csv
  - vcl_ts_US.csv
container_name:
- obis-biodiversity
- vestas
prefix:
  obis-biodiversity: Hackathons/
  vestas: ''
storage_account_key:
  obis-biodiversity: si=wind_europe_hackathon&spr=https&sv=2022-11-02&sr=c&sig=MBp4L6GnrxZmKaJZ9i7Q3RV8i9kcUAj9QnvNyofmKco%3D
  vestas: si=vestas_hackathon_policy&spr=https&sv=2022-11-02&sr=c&sig=M8agHJFDQcypdAvMEy7%2FATkjDHPI7wTCmRL4pbmEgsc%3D
storage_account_name: https://stodpdaskuserspace.blob.core.windows.net
