blob_chunk:
  obis-biodiversity:
  - parquet/obis_20220710_partitioned/chunk_0.parquet
  - parquet/obis_20220710_partitioned/chunk_1.parquet
  - parquet/obis_20220710_partitioned/chunk_10.parquet
  - parquet/obis_20220710_partitioned/chunk_100.parquet
  - parquet/obis_20220710_partitioned/chunk_101.parquet
  - parquet/obis_20220710_partitioned/chunk_102.parquet
  - parquet/obis_20220710_partitioned/chunk_103.parquet
  - parquet/obis_20220710_partitioned/chunk_104.parquet
  - parquet/obis_20220710_partitioned/chunk_105.parquet
  - parquet/obis_20220710_partitioned/chunk_106.parquet
  - parquet/obis_20220710_partitioned/chunk_107.parquet
  - parquet/obis_20220710_partitioned/chunk_108.parquet
  - parquet/obis_20220710_partitioned/chunk_109.parquet
  - parquet/obis_20220710_partitioned/chunk_11.parquet
  - parquet/obis_20220710_partitioned/chunk_110.parquet
  - parquet/obis_20220710_partitioned/chunk_111.parquet
  - parquet/obis_20220710_partitioned/chunk_112.parquet
  - parquet/obis_20220710_partitioned/chunk_113.parquet
  - parquet/obis_20220710_partitioned/chunk_114.parquet
  - parquet/obis_20220710_partitioned/chunk_115.parquet
  - parquet/obis_20220710_partitioned/chunk_116.parquet
  - parquet/obis_20220710_partitioned/chunk_117.parquet
  - parquet/obis_20220710_partitioned/chunk_118.parquet
  - parquet/obis_20220710_partitioned/chunk_119.parquet
  - parquet/obis_20220710_partitioned/chunk_12.parquet
  - parquet/obis_20220710_partitioned/chunk_120.parquet
  - parquet/obis_20220710_partitioned/chunk_121.parquet
  - parquet/obis_20220710_partitioned/chunk_122.parquet
  - parquet/obis_20220710_partitioned/chunk_123.parquet
  - parquet/obis_20220710_partitioned/chunk_124.parquet
  - parquet/obis_20220710_partitioned/chunk_125.parquet
  - parquet/obis_20220710_partitioned/chunk_126.parquet
  - parquet/obis_20220710_partitioned/chunk_127.parquet
  - parquet/obis_20220710_partitioned/chunk_128.parquet
  - parquet/obis_20220710_partitioned/chunk_129.parquet
  - parquet/obis_20220710_partitioned/chunk_13.parquet
  - parquet/obis_20220710_partitioned/chunk_130.parquet
  - parquet/obis_20220710_partitioned/chunk_131.parquet
  - parquet/obis_20220710_partitioned/chunk_14.parquet
  - parquet/obis_20220710_partitioned/chunk_15.parquet
  - parquet/obis_20220710_partitioned/chunk_16.parquet
  - parquet/obis_20220710_partitioned/chunk_17.parquet
  - parquet/obis_20220710_partitioned/chunk_18.parquet
  - parquet/obis_20220710_partitioned/chunk_19.parquet
  - parquet/obis_20220710_partitioned/chunk_2.parquet
  - parquet/obis_20220710_partitioned/chunk_20.parquet
  - parquet/obis_20220710_partitioned/chunk_21.parquet
  - parquet/obis_20220710_partitioned/chunk_22.parquet
  - parquet/obis_20220710_partitioned/chunk_23.parquet
  - parquet/obis_20220710_partitioned/chunk_24.parquet
  - parquet/obis_20220710_partitioned/chunk_25.parquet
  - parquet/obis_20220710_partitioned/chunk_26.parquet
  - parquet/obis_20220710_partitioned/chunk_27.parquet
  - parquet/obis_20220710_partitioned/chunk_28.parquet
  - parquet/obis_20220710_partitioned/chunk_29.parquet
  - parquet/obis_20220710_partitioned/chunk_3.parquet
  - parquet/obis_20220710_partitioned/chunk_30.parquet
  - parquet/obis_20220710_partitioned/chunk_31.parquet
  - parquet/obis_20220710_partitioned/chunk_32.parquet
  - parquet/obis_20220710_partitioned/chunk_33.parquet
  - parquet/obis_20220710_partitioned/chunk_34.parquet
  - parquet/obis_20220710_partitioned/chunk_35.parquet
  - parquet/obis_20220710_partitioned/chunk_36.parquet
  - parquet/obis_20220710_partitioned/chunk_37.parquet
  - parquet/obis_20220710_partitioned/chunk_38.parquet
  - parquet/obis_20220710_partitioned/chunk_39.parquet
  - parquet/obis_20220710_partitioned/chunk_4.parquet
  - parquet/obis_20220710_partitioned/chunk_40.parquet
  - parquet/obis_20220710_partitioned/chunk_41.parquet
  - parquet/obis_20220710_partitioned/chunk_42.parquet
  - parquet/obis_20220710_partitioned/chunk_43.parquet
  - parquet/obis_20220710_partitioned/chunk_44.parquet
  - parquet/obis_20220710_partitioned/chunk_45.parquet
  - parquet/obis_20220710_partitioned/chunk_46.parquet
  - parquet/obis_20220710_partitioned/chunk_47.parquet
  - parquet/obis_20220710_partitioned/chunk_48.parquet
  - parquet/obis_20220710_partitioned/chunk_49.parquet
  - parquet/obis_20220710_partitioned/chunk_5.parquet
  - parquet/obis_20220710_partitioned/chunk_50.parquet
  - parquet/obis_20220710_partitioned/chunk_51.parquet
  - parquet/obis_20220710_partitioned/chunk_52.parquet
  - parquet/obis_20220710_partitioned/chunk_53.parquet
  - parquet/obis_20220710_partitioned/chunk_54.parquet
  - parquet/obis_20220710_partitioned/chunk_55.parquet
  - parquet/obis_20220710_partitioned/chunk_56.parquet
  - parquet/obis_20220710_partitioned/chunk_57.parquet
  - parquet/obis_20220710_partitioned/chunk_58.parquet
  - parquet/obis_20220710_partitioned/chunk_59.parquet
  - parquet/obis_20220710_partitioned/chunk_6.parquet
  - parquet/obis_20220710_partitioned/chunk_60.parquet
  - parquet/obis_20220710_partitioned/chunk_61.parquet
  - parquet/obis_20220710_partitioned/chunk_62.parquet
  - parquet/obis_20220710_partitioned/chunk_63.parquet
  - parquet/obis_20220710_partitioned/chunk_64.parquet
  - parquet/obis_20220710_partitioned/chunk_65.parquet
  - parquet/obis_20220710_partitioned/chunk_66.parquet
  - parquet/obis_20220710_partitioned/chunk_67.parquet
  - parquet/obis_20220710_partitioned/chunk_68.parquet
  - parquet/obis_20220710_partitioned/chunk_69.parquet
  - parquet/obis_20220710_partitioned/chunk_7.parquet
  - parquet/obis_20220710_partitioned/chunk_70.parquet
  - parquet/obis_20220710_partitioned/chunk_71.parquet
  - parquet/obis_20220710_partitioned/chunk_72.parquet
  - parquet/obis_20220710_partitioned/chunk_73.parquet
  - parquet/obis_20220710_partitioned/chunk_74.parquet
  - parquet/obis_20220710_partitioned/chunk_75.parquet
  - parquet/obis_20220710_partitioned/chunk_76.parquet
  - parquet/obis_20220710_partitioned/chunk_77.parquet
  - parquet/obis_20220710_partitioned/chunk_78.parquet
  - parquet/obis_20220710_partitioned/chunk_79.parquet
  - parquet/obis_20220710_partitioned/chunk_8.parquet
  - parquet/obis_20220710_partitioned/chunk_80.parquet
  - parquet/obis_20220710_partitioned/chunk_81.parquet
  - parquet/obis_20220710_partitioned/chunk_82.parquet
  - parquet/obis_20220710_partitioned/chunk_83.parquet
  - parquet/obis_20220710_partitioned/chunk_84.parquet
  - parquet/obis_20220710_partitioned/chunk_85.parquet
  - parquet/obis_20220710_partitioned/chunk_86.parquet
  - parquet/obis_20220710_partitioned/chunk_87.parquet
  - parquet/obis_20220710_partitioned/chunk_88.parquet
  - parquet/obis_20220710_partitioned/chunk_89.parquet
  - parquet/obis_20220710_partitioned/chunk_9.parquet
  - parquet/obis_20220710_partitioned/chunk_90.parquet
  - parquet/obis_20220710_partitioned/chunk_91.parquet
  - parquet/obis_20220710_partitioned/chunk_92.parquet
  - parquet/obis_20220710_partitioned/chunk_93.parquet
  - parquet/obis_20220710_partitioned/chunk_94.parquet
  - parquet/obis_20220710_partitioned/chunk_95.parquet
  - parquet/obis_20220710_partitioned/chunk_96.parquet
  - parquet/obis_20220710_partitioned/chunk_97.parquet
  - parquet/obis_20220710_partitioned/chunk_98.parquet
  - parquet/obis_20220710_partitioned/chunk_99.parquet
  vestas:
  - vcl_ts_CN.csv
  - vcl_ts_NL.csv
  - vcl_ts_NO.csv
  - vcl_ts_US.csv
container_name:
- obis-biodiversity
- vestas
prefix:
  obis-biodiversity: Hackathons/
  vestas: ''
storage_account_key:
  obis-biodiversity: si=wind_europe_hackathon&spr=https&sv=2022-11-02&sr=c&sig=MBp4L6GnrxZmKaJZ9i7Q3RV8i9kcUAj9QnvNyofmKco%3D
  vestas: si=vestas_hackathon_policy&spr=https&sv=2022-11-02&sr=c&sig=M8agHJFDQcypdAvMEy7%2FATkjDHPI7wTCmRL4pbmEgsc%3D
storage_account_name: https://stodpdaskuserspace.blob.core.windows.net
