name: Docker Image CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Generate Docker metadata
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: |
            oceandata.azurecr.io/odc-example-notebooks-testrunner
          flavor: |
            latest=true
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v1
      - uses: azure/docker-login@v1
        with:
          login-server: oceandata.azurecr.io
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}
      - uses: actions/checkout@v3
      - name: Build and push the docker image
        uses: docker/build-push-action@v2
        env:
          DOCKER_BUILDKIT: 1
        with:
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}


  run_tests_obis-ipynb:
    needs: build
    runs-on: ubuntu-latest
    container:
      image: oceandata.azurecr.io/odc-example-notebooks-testrunner:latest
      credentials:
        username: ${{ secrets.ACR_USERNAME }}
        password: ${{ secrets.ACR_PASSWORD }}

    steps:
      - uses: actions/checkout@v3
      - run: ls -l $GITHUB_WORKSPACE
      - run: ls -l $GITHUB_WORKSPACE/..
      - name: List nox sessions
        run: nox -l -f $GITHUB_WORKSPACE/noxfile.py
      - name: Run tests for obis-ipynb
        run:
          nox -s "test_notebook-3.9(notebook_file='/__w/OceanDataConnector/OceanDataConnector/data/OBIS/OBIS.ipynb')" -f $GITHUB_WORKSPACE/noxfile.py
        env:
          ODE_CONNECTION_STR: ${{ secrets.ODE_CONNECTION_STR }}
          ODE_MAPBOX_API_TOKEN: ${{ secrets.ODE_MAPBOX_API_TOKEN }}
          DATABASE_URL: ${{ secrets.ODC_DATABASE_URL }}

  run_tests_marineregions-ipynb:
    needs: build
    runs-on: ubuntu-latest
    container:
      image: oceandata.azurecr.io/odc-example-notebooks-testrunner:latest
      credentials:
        username: ${{ secrets.ACR_USERNAME }}
        password: ${{ secrets.ACR_PASSWORD }}

    steps:
      - uses: actions/checkout@v3
      - run: ls -l $GITHUB_WORKSPACE
      - run: ls -l $GITHUB_WORKSPACE/..
      - name: List nox sessions
        run: nox -l -f $GITHUB_WORKSPACE/noxfile.py
      - name: Run tests for marineregions-ipynb
        run:
          nox -s "test_notebook-3.9(notebook_file='/__w/OceanDataConnector/OceanDataConnector/SDK/ExampleNotebooks/MarineRegions.ipynb')" -f $GITHUB_WORKSPACE/noxfile.py
        env:
          ODE_CONNECTION_STR: ${{ secrets.ODE_CONNECTION_STR }}
          ODE_MAPBOX_API_TOKEN: ${{ secrets.ODE_MAPBOX_API_TOKEN }}
          DATABASE_URL: ${{ secrets.ODC_DATABASE_URL }}

  run_tests_worms-ipynb:
    needs: build
    runs-on: ubuntu-latest
    container:
      image: oceandata.azurecr.io/odc-example-notebooks-testrunner:latest
      credentials:
        username: ${{ secrets.ACR_USERNAME }}
        password: ${{ secrets.ACR_PASSWORD }}

    steps:
      - uses: actions/checkout@v3
      - run: ls -l $GITHUB_WORKSPACE
      - run: ls -l $GITHUB_WORKSPACE/..
      - name: List nox sessions
        run: nox -l -f $GITHUB_WORKSPACE/noxfile.py
      - name: Run tests for worms-ipynb
        run:
          nox -s "test_notebook-3.9(notebook_file='/__w/OceanDataConnector/OceanDataConnector/data/Worms/WoRMS.ipynb')" -f $GITHUB_WORKSPACE/noxfile.py
        env:
          ODE_CONNECTION_STR: ${{ secrets.ODE_CONNECTION_STR }}
          ODE_MAPBOX_API_TOKEN: ${{ secrets.ODE_MAPBOX_API_TOKEN }}
          DATABASE_URL: ${{ secrets.ODC_DATABASE_URL }}

  run_tests_lusedata-app-ipynb:
    needs: build
    runs-on: ubuntu-latest
    container:
      image: oceandata.azurecr.io/odc-example-notebooks-testrunner:latest
      credentials:
        username: ${{ secrets.ACR_USERNAME }}
        password: ${{ secrets.ACR_PASSWORD }}

    steps:
      - uses: actions/checkout@v3
      - run: ls -l $GITHUB_WORKSPACE
      - run: ls -l $GITHUB_WORKSPACE/..
      - name: List nox sessions
        run: nox -l -f $GITHUB_WORKSPACE/noxfile.py
      - name: Run tests for lusedata-app-ipynb
        run:
          nox -s "test_notebook-3.9(notebook_file='/__w/OceanDataConnector/OceanDataConnector/data/lusedata/Lusedata_app.ipynb')" -f $GITHUB_WORKSPACE/noxfile.py
        env:
          ODE_CONNECTION_STR: ${{ secrets.ODE_CONNECTION_STR }}
          ODE_MAPBOX_API_TOKEN: ${{ secrets.ODE_MAPBOX_API_TOKEN }}
          DATABASE_URL: ${{ secrets.ODC_DATABASE_URL }}

  run_tests_lusedatapull-ipynb:
    needs: build
    runs-on: ubuntu-latest
    container:
      image: oceandata.azurecr.io/odc-example-notebooks-testrunner:latest
      credentials:
        username: ${{ secrets.ACR_USERNAME }}
        password: ${{ secrets.ACR_PASSWORD }}

    steps:
      - uses: actions/checkout@v3
      - run: ls -l $GITHUB_WORKSPACE
      - run: ls -l $GITHUB_WORKSPACE/..
      - name: List nox sessions
        run: nox -l -f $GITHUB_WORKSPACE/noxfile.py
      - name: Run tests for lusedatapull-ipynb
        run:
          nox -s "test_notebook-3.9(notebook_file='/__w/OceanDataConnector/OceanDataConnector/data/lusedata/LusedataPull.ipynb')" -f $GITHUB_WORKSPACE/noxfile.py
        env:
          ODE_CONNECTION_STR: ${{ secrets.ODE_CONNECTION_STR }}
          ODE_MAPBOX_API_TOKEN: ${{ secrets.ODE_MAPBOX_API_TOKEN }}
          DATABASE_URL: ${{ secrets.ODC_DATABASE_URL }}

  run_tests_gebco-bathymetry-ipynb:
    needs: build
    runs-on: ubuntu-latest
    container:
      image: oceandata.azurecr.io/odc-example-notebooks-testrunner:latest
      credentials:
        username: ${{ secrets.ACR_USERNAME }}
        password: ${{ secrets.ACR_PASSWORD }}

    steps:
      - uses: actions/checkout@v3
      - run: ls -l $GITHUB_WORKSPACE
      - run: ls -l $GITHUB_WORKSPACE/..
      - name: List nox sessions
        run: nox -l -f $GITHUB_WORKSPACE/noxfile.py
      - name: Run tests for gebco-bathymetry-ipynb
        run:
          nox -s "test_notebook-3.9(notebook_file='/__w/OceanDataConnector/OceanDataConnector/data/GEBCO Bathymetry/GEBCO_Bathymetry.ipynb')" -f $GITHUB_WORKSPACE/noxfile.py
        env:
          ODE_CONNECTION_STR: ${{ secrets.ODE_CONNECTION_STR }}
          ODE_MAPBOX_API_TOKEN: ${{ secrets.ODE_MAPBOX_API_TOKEN }}
          DATABASE_URL: ${{ secrets.ODC_DATABASE_URL }}

  run_tests_protectedseas-mpa-ipynb:
    needs: build
    runs-on: ubuntu-latest
    container:
      image: oceandata.azurecr.io/odc-example-notebooks-testrunner:latest
      credentials:
        username: ${{ secrets.ACR_USERNAME }}
        password: ${{ secrets.ACR_PASSWORD }}

    steps:
      - uses: actions/checkout@v3
      - run: ls -l $GITHUB_WORKSPACE
      - run: ls -l $GITHUB_WORKSPACE/..
      - name: List nox sessions
        run: nox -l -f $GITHUB_WORKSPACE/noxfile.py
      - name: Run tests for protectedseas-mpa-ipynb
        run:
          nox -s "test_notebook-3.9(notebook_file='/__w/OceanDataConnector/OceanDataConnector/data/ProtectedSeas MPA/ProtectedSeas_MPA.ipynb')" -f $GITHUB_WORKSPACE/noxfile.py
        env:
          ODE_CONNECTION_STR: ${{ secrets.ODE_CONNECTION_STR }}
          ODE_MAPBOX_API_TOKEN: ${{ secrets.ODE_MAPBOX_API_TOKEN }}
          DATABASE_URL: ${{ secrets.ODC_DATABASE_URL }}

  run_tests_worldoceandatabase-ipynb:
    needs: build
    runs-on: ubuntu-latest
    container:
      image: oceandata.azurecr.io/odc-example-notebooks-testrunner:latest
      credentials:
        username: ${{ secrets.ACR_USERNAME }}
        password: ${{ secrets.ACR_PASSWORD }}

    steps:
      - uses: actions/checkout@v3
      - run: ls -l $GITHUB_WORKSPACE
      - run: ls -l $GITHUB_WORKSPACE/..
      - name: List nox sessions
        run: nox -l -f $GITHUB_WORKSPACE/noxfile.py
      - name: Run tests for worldoceandatabase-ipynb
        run:
          nox -s "test_notebook-3.9(notebook_file='/__w/OceanDataConnector/OceanDataConnector/data/World Ocean Database/WorldOceanDatabase.ipynb')" -f $GITHUB_WORKSPACE/noxfile.py
        env:
          ODE_CONNECTION_STR: ${{ secrets.ODE_CONNECTION_STR }}
          ODE_MAPBOX_API_TOKEN: ${{ secrets.ODE_MAPBOX_API_TOKEN }}
          DATABASE_URL: ${{ secrets.ODC_DATABASE_URL }}

  run_tests_worldoceanatlas-ipynb:
    needs: build
    runs-on: ubuntu-latest
    container:
      image: oceandata.azurecr.io/odc-example-notebooks-testrunner:latest
      credentials:
        username: ${{ secrets.ACR_USERNAME }}
        password: ${{ secrets.ACR_PASSWORD }}

    steps:
      - uses: actions/checkout@v3
      - run: ls -l $GITHUB_WORKSPACE
      - run: ls -l $GITHUB_WORKSPACE/..
      - name: List nox sessions
        run: nox -l -f $GITHUB_WORKSPACE/noxfile.py
      - name: Run tests for worldoceanatlas-ipynb
        run:
          nox -s "test_notebook-3.9(notebook_file='/__w/OceanDataConnector/OceanDataConnector/data/World Ocean Atlas/WorldOceanAtlas.ipynb')" -f $GITHUB_WORKSPACE/noxfile.py
        env:
          ODE_CONNECTION_STR: ${{ secrets.ODE_CONNECTION_STR }}
          ODE_MAPBOX_API_TOKEN: ${{ secrets.ODE_MAPBOX_API_TOKEN }}
          DATABASE_URL: ${{ secrets.ODC_DATABASE_URL }}

  run_tests_noaa-crw-time-series-classification-ipynb:
    needs: build
    runs-on: ubuntu-latest
    container:
      image: oceandata.azurecr.io/odc-example-notebooks-testrunner:latest
      credentials:
        username: ${{ secrets.ACR_USERNAME }}
        password: ${{ secrets.ACR_PASSWORD }}

    steps:
      - uses: actions/checkout@v3
      - run: ls -l $GITHUB_WORKSPACE
      - run: ls -l $GITHUB_WORKSPACE/..
      - name: List nox sessions
        run: nox -l -f $GITHUB_WORKSPACE/noxfile.py
      - name: Run tests for noaa-crw-time-series-classification-ipynb
        run:
          nox -s "test_notebook-3.9(notebook_file='/__w/OceanDataConnector/OceanDataConnector/data/NOAA Coral Reef Watch/NOAA_CRW_time_series_classification.ipynb')" -f $GITHUB_WORKSPACE/noxfile.py
        env:
          ODE_CONNECTION_STR: ${{ secrets.ODE_CONNECTION_STR }}
          ODE_MAPBOX_API_TOKEN: ${{ secrets.ODE_MAPBOX_API_TOKEN }}
          DATABASE_URL: ${{ secrets.ODC_DATABASE_URL }}

  run_tests_noaa-crw-bleaching-classifier-ipynb:
    needs: build
    runs-on: ubuntu-latest
    container:
      image: oceandata.azurecr.io/odc-example-notebooks-testrunner:latest
      credentials:
        username: ${{ secrets.ACR_USERNAME }}
        password: ${{ secrets.ACR_PASSWORD }}

    steps:
      - uses: actions/checkout@v3
      - run: ls -l $GITHUB_WORKSPACE
      - run: ls -l $GITHUB_WORKSPACE/..
      - name: List nox sessions
        run: nox -l -f $GITHUB_WORKSPACE/noxfile.py
      - name: Run tests for noaa-crw-bleaching-classifier-ipynb
        run:
          nox -s "test_notebook-3.9(notebook_file='/__w/OceanDataConnector/OceanDataConnector/data/NOAA Coral Reef Watch/NOAA_CRW_bleaching_classifier.ipynb')" -f $GITHUB_WORKSPACE/noxfile.py
        env:
          ODE_CONNECTION_STR: ${{ secrets.ODE_CONNECTION_STR }}
          ODE_MAPBOX_API_TOKEN: ${{ secrets.ODE_MAPBOX_API_TOKEN }}
          DATABASE_URL: ${{ secrets.ODC_DATABASE_URL }}

  run_tests_wids-crw-bleaching-ipynb:
    needs: build
    runs-on: ubuntu-latest
    container:
      image: oceandata.azurecr.io/odc-example-notebooks-testrunner:latest
      credentials:
        username: ${{ secrets.ACR_USERNAME }}
        password: ${{ secrets.ACR_PASSWORD }}

    steps:
      - uses: actions/checkout@v3
      - run: ls -l $GITHUB_WORKSPACE
      - run: ls -l $GITHUB_WORKSPACE/..
      - name: List nox sessions
        run: nox -l -f $GITHUB_WORKSPACE/noxfile.py
      - name: Run tests for wids-crw-bleaching-ipynb
        run:
          nox -s "test_notebook-3.9(notebook_file='/__w/OceanDataConnector/OceanDataConnector/data/NOAA Coral Reef Watch/WiDS/WiDS_CRW_bleaching.ipynb')" -f $GITHUB_WORKSPACE/noxfile.py
        env:
          ODE_CONNECTION_STR: ${{ secrets.ODE_CONNECTION_STR }}
          ODE_MAPBOX_API_TOKEN: ${{ secrets.ODE_MAPBOX_API_TOKEN }}
          DATABASE_URL: ${{ secrets.ODC_DATABASE_URL }}

  run_tests_timeseries-classification-ipynb:
    needs: build
    runs-on: ubuntu-latest
    container:
      image: oceandata.azurecr.io/odc-example-notebooks-testrunner:latest
      credentials:
        username: ${{ secrets.ACR_USERNAME }}
        password: ${{ secrets.ACR_PASSWORD }}

    steps:
      - uses: actions/checkout@v3
      - run: ls -l $GITHUB_WORKSPACE
      - run: ls -l $GITHUB_WORKSPACE/..
      - name: List nox sessions
        run: nox -l -f $GITHUB_WORKSPACE/noxfile.py
      - name: Run tests for timeseries-classification-ipynb
        run:
          nox -s "test_notebook-3.9(notebook_file='/__w/OceanDataConnector/OceanDataConnector/data/NOAA Coral Reef Watch/WiDS/timeseries_classification.ipynb')" -f $GITHUB_WORKSPACE/noxfile.py
        env:
          ODE_CONNECTION_STR: ${{ secrets.ODE_CONNECTION_STR }}
          ODE_MAPBOX_API_TOKEN: ${{ secrets.ODE_MAPBOX_API_TOKEN }}
          DATABASE_URL: ${{ secrets.ODC_DATABASE_URL }}

  run_tests_wids-classification-ipynb:
    needs: build
    runs-on: ubuntu-latest
    container:
      image: oceandata.azurecr.io/odc-example-notebooks-testrunner:latest
      credentials:
        username: ${{ secrets.ACR_USERNAME }}
        password: ${{ secrets.ACR_PASSWORD }}

    steps:
      - uses: actions/checkout@v3
      - run: ls -l $GITHUB_WORKSPACE
      - run: ls -l $GITHUB_WORKSPACE/..
      - name: List nox sessions
        run: nox -l -f $GITHUB_WORKSPACE/noxfile.py
      - name: Run tests for wids-classification-ipynb
        run:
          nox -s "test_notebook-3.9(notebook_file='/__w/OceanDataConnector/OceanDataConnector/data/NOAA Coral Reef Watch/WiDS/WiDS_classification.ipynb')" -f $GITHUB_WORKSPACE/noxfile.py
        env:
          ODE_CONNECTION_STR: ${{ secrets.ODE_CONNECTION_STR }}
          ODE_MAPBOX_API_TOKEN: ${{ secrets.ODE_MAPBOX_API_TOKEN }}
          DATABASE_URL: ${{ secrets.ODC_DATABASE_URL }}

  run_tests_oceanlab-ipynb:
    needs: build
    runs-on: ubuntu-latest
    container:
      image: oceandata.azurecr.io/odc-example-notebooks-testrunner:latest
      credentials:
        username: ${{ secrets.ACR_USERNAME }}
        password: ${{ secrets.ACR_PASSWORD }}

    steps:
      - uses: actions/checkout@v3
      - run: ls -l $GITHUB_WORKSPACE
      - run: ls -l $GITHUB_WORKSPACE/..
      - name: List nox sessions
        run: nox -l -f $GITHUB_WORKSPACE/noxfile.py
      - name: Run tests for oceanlab-ipynb
        run:
          nox -s "test_notebook-3.9(notebook_file='/__w/OceanDataConnector/OceanDataConnector/data/OceanLab/OceanLab.ipynb')" -f $GITHUB_WORKSPACE/noxfile.py
        env:
          ODE_CONNECTION_STR: ${{ secrets.ODE_CONNECTION_STR }}
          ODE_MAPBOX_API_TOKEN: ${{ secrets.ODE_MAPBOX_API_TOKEN }}
          DATABASE_URL: ${{ secrets.ODC_DATABASE_URL }}

  run_tests_griddedvesselemissionsandtraffic-ipynb:
    needs: build
    runs-on: ubuntu-latest
    container:
      image: oceandata.azurecr.io/odc-example-notebooks-testrunner:latest
      credentials:
        username: ${{ secrets.ACR_USERNAME }}
        password: ${{ secrets.ACR_PASSWORD }}

    steps:
      - uses: actions/checkout@v3
      - run: ls -l $GITHUB_WORKSPACE
      - run: ls -l $GITHUB_WORKSPACE/..
      - name: List nox sessions
        run: nox -l -f $GITHUB_WORKSPACE/noxfile.py
      - name: Run tests for griddedvesselemissionsandtraffic-ipynb
        run:
          nox -s "test_notebook-3.9(notebook_file='/__w/OceanDataConnector/OceanDataConnector/data/GlobalVesselEmissions/GriddedVesselEmissionsAndTraffic.ipynb')" -f $GITHUB_WORKSPACE/noxfile.py
        env:
          ODE_CONNECTION_STR: ${{ secrets.ODE_CONNECTION_STR }}
          ODE_MAPBOX_API_TOKEN: ${{ secrets.ODE_MAPBOX_API_TOKEN }}
          DATABASE_URL: ${{ secrets.ODC_DATABASE_URL }}

  run_tests_emodnet-human-activity-ipynb:
    needs: build
    runs-on: ubuntu-latest
    container:
      image: oceandata.azurecr.io/odc-example-notebooks-testrunner:latest
      credentials:
        username: ${{ secrets.ACR_USERNAME }}
        password: ${{ secrets.ACR_PASSWORD }}

    steps:
      - uses: actions/checkout@v3
      - run: ls -l $GITHUB_WORKSPACE
      - run: ls -l $GITHUB_WORKSPACE/..
      - name: List nox sessions
        run: nox -l -f $GITHUB_WORKSPACE/noxfile.py
      - name: Run tests for emodnet-human-activity-ipynb
        run:
          nox -s "test_notebook-3.9(notebook_file='/__w/OceanDataConnector/OceanDataConnector/data/EMODnet_Human_Activity/EMODnet_human_activity.ipynb')" -f $GITHUB_WORKSPACE/noxfile.py
        env:
          ODE_CONNECTION_STR: ${{ secrets.ODE_CONNECTION_STR }}
          ODE_MAPBOX_API_TOKEN: ${{ secrets.ODE_MAPBOX_API_TOKEN }}
          DATABASE_URL: ${{ secrets.ODC_DATABASE_URL }}

  run_tests_simulator-comparing-emissions-ipynb:
    needs: build
    runs-on: ubuntu-latest
    container:
      image: oceandata.azurecr.io/odc-example-notebooks-testrunner:latest
      credentials:
        username: ${{ secrets.ACR_USERNAME }}
        password: ${{ secrets.ACR_PASSWORD }}

    steps:
      - uses: actions/checkout@v3
      - run: ls -l $GITHUB_WORKSPACE
      - run: ls -l $GITHUB_WORKSPACE/..
      - name: List nox sessions
        run: nox -l -f $GITHUB_WORKSPACE/noxfile.py
      - name: Run tests for simulator-comparing-emissions-ipynb
        run:
          nox -s "test_notebook-3.9(notebook_file='/__w/OceanDataConnector/OceanDataConnector/Data Products/Simulator, Comparing Emissions.ipynb')" -f $GITHUB_WORKSPACE/noxfile.py
        env:
          ODE_CONNECTION_STR: ${{ secrets.ODE_CONNECTION_STR }}
          ODE_MAPBOX_API_TOKEN: ${{ secrets.ODE_MAPBOX_API_TOKEN }}
          DATABASE_URL: ${{ secrets.ODC_DATABASE_URL }}
