name: Docker Image CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: azure/docker-login@v1
        with:
          login-server: oceandata.azurecr.io
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}
      - name: Build the Docker image
        run:
          docker build . --tag oceandata.azurecr.io/gh-odc-test-notebooks:latest
      - name: Push docker image
        run: docker push oceandata.azurecr.io/gh-odc-test-notebooks:latest
  run_tests:
    runs-on: ubuntu-latest
    needs: build
    container:
      image: oceandata.azurecr.io/gh-odc-test-notebooks:latest
    steps:
      - name: Run tests
        run: nox
        env:
          DATABASE_URL: ${{ secrets.ODC_DATABASE_URL }}
