name: Docker Image CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Generate Docker metadata
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: |
            oceandata.azurecr.io/odc-example-notebooks-testrunner
          flavor: |
            latest=true
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v1
      - uses: azure/docker-login@v1
        with:
          login-server: oceandata.azurecr.io
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}
      - uses: actions/checkout@v3
      - name: Build and push the docker image
        uses: docker/build-push-action@v2
        env:
          DOCKER_BUILDKIT: 1
        with:
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}


  run_tests_obis-ipynb:
    needs: build
    runs-on: ubuntu-latest
    container:
      image: oceandata.azurecr.io/odc-example-notebooks-testrunner:latest
      credentials:
        username: ${{ secrets.ACR_USERNAME }}
        password: ${{ secrets.ACR_PASSWORD }}

    steps:
      - name: List nox sessions
        run: nox -l -f /src/noxfile.py
      - name: Run tests for obis-ipynb
        run:
          nox -s "test_notebook-3.9(notebook_file='/src/data/OBIS/OBIS.ipynb')" -f /src/noxfile.py
        env:
          ODE_CONNECTION_STR: ${{ secrets.ODE_CONNECTION_STR }}
          ODE_MAPBOX_API_TOKEN: ${{ secrets.ODE_MAPBOX_API_TOKEN }}
          DATABASE_URL: ${{ secrets.ODC_DATABASE_URL }}

  run_tests_obis-checkpoint-ipynb:
    needs: build
    runs-on: ubuntu-latest
    container:
      image: oceandata.azurecr.io/odc-example-notebooks-testrunner:latest
      credentials:
        username: ${{ secrets.ACR_USERNAME }}
        password: ${{ secrets.ACR_PASSWORD }}

    steps:
      - name: List nox sessions
        run: nox -l -f /src/noxfile.py
      - name: Run tests for obis-checkpoint-ipynb
        run:
          nox -s "test_notebook-3.9(notebook_file='/src/data/OBIS/.ipynb_checkpoints/OBIS-checkpoint.ipynb')" -f /src/noxfile.py
        env:
          ODE_CONNECTION_STR: ${{ secrets.ODE_CONNECTION_STR }}
          ODE_MAPBOX_API_TOKEN: ${{ secrets.ODE_MAPBOX_API_TOKEN }}
          DATABASE_URL: ${{ secrets.ODC_DATABASE_URL }}

  run_tests_marineregions-ipynb:
    needs: build
    runs-on: ubuntu-latest
    container:
      image: oceandata.azurecr.io/odc-example-notebooks-testrunner:latest
      credentials:
        username: ${{ secrets.ACR_USERNAME }}
        password: ${{ secrets.ACR_PASSWORD }}

    steps:
      - name: List nox sessions
        run: nox -l -f /src/noxfile.py
      - name: Run tests for marineregions-ipynb
        run:
          nox -s "test_notebook-3.9(notebook_file='/src/SDK/ExampleNotebooks/MarineRegions.ipynb')" -f /src/noxfile.py
        env:
          ODE_CONNECTION_STR: ${{ secrets.ODE_CONNECTION_STR }}
          ODE_MAPBOX_API_TOKEN: ${{ secrets.ODE_MAPBOX_API_TOKEN }}
          DATABASE_URL: ${{ secrets.ODC_DATABASE_URL }}

  run_tests_marineregions-checkpoint-ipynb:
    needs: build
    runs-on: ubuntu-latest
    container:
      image: oceandata.azurecr.io/odc-example-notebooks-testrunner:latest
      credentials:
        username: ${{ secrets.ACR_USERNAME }}
        password: ${{ secrets.ACR_PASSWORD }}

    steps:
      - name: List nox sessions
        run: nox -l -f /src/noxfile.py
      - name: Run tests for marineregions-checkpoint-ipynb
        run:
          nox -s "test_notebook-3.9(notebook_file='/src/data/Marine Regions/.ipynb_checkpoints/MarineRegions-checkpoint.ipynb')" -f /src/noxfile.py
        env:
          ODE_CONNECTION_STR: ${{ secrets.ODE_CONNECTION_STR }}
          ODE_MAPBOX_API_TOKEN: ${{ secrets.ODE_MAPBOX_API_TOKEN }}
          DATABASE_URL: ${{ secrets.ODC_DATABASE_URL }}

  run_tests_worms-ipynb:
    needs: build
    runs-on: ubuntu-latest
    container:
      image: oceandata.azurecr.io/odc-example-notebooks-testrunner:latest
      credentials:
        username: ${{ secrets.ACR_USERNAME }}
        password: ${{ secrets.ACR_PASSWORD }}

    steps:
      - name: List nox sessions
        run: nox -l -f /src/noxfile.py
      - name: Run tests for worms-ipynb
        run:
          nox -s "test_notebook-3.9(notebook_file='/src/data/Worms/WoRMS.ipynb')" -f /src/noxfile.py
        env:
          ODE_CONNECTION_STR: ${{ secrets.ODE_CONNECTION_STR }}
          ODE_MAPBOX_API_TOKEN: ${{ secrets.ODE_MAPBOX_API_TOKEN }}
          DATABASE_URL: ${{ secrets.ODC_DATABASE_URL }}

  run_tests_lusedata-ipynb:
    needs: build
    runs-on: ubuntu-latest
    container:
      image: oceandata.azurecr.io/odc-example-notebooks-testrunner:latest
      credentials:
        username: ${{ secrets.ACR_USERNAME }}
        password: ${{ secrets.ACR_PASSWORD }}

    steps:
      - name: List nox sessions
        run: nox -l -f /src/noxfile.py
      - name: Run tests for lusedata-ipynb
        run:
          nox -s "test_notebook-3.9(notebook_file='/src/data/lusedata/Lusedata.ipynb')" -f /src/noxfile.py
        env:
          ODE_CONNECTION_STR: ${{ secrets.ODE_CONNECTION_STR }}
          ODE_MAPBOX_API_TOKEN: ${{ secrets.ODE_MAPBOX_API_TOKEN }}
          DATABASE_URL: ${{ secrets.ODC_DATABASE_URL }}

  run_tests_lusedata-checkpoint-ipynb:
    needs: build
    runs-on: ubuntu-latest
    container:
      image: oceandata.azurecr.io/odc-example-notebooks-testrunner:latest
      credentials:
        username: ${{ secrets.ACR_USERNAME }}
        password: ${{ secrets.ACR_PASSWORD }}

    steps:
      - name: List nox sessions
        run: nox -l -f /src/noxfile.py
      - name: Run tests for lusedata-checkpoint-ipynb
        run:
          nox -s "test_notebook-3.9(notebook_file='/src/data/lusedata/.ipynb_checkpoints/Lusedata-checkpoint.ipynb')" -f /src/noxfile.py
        env:
          ODE_CONNECTION_STR: ${{ secrets.ODE_CONNECTION_STR }}
          ODE_MAPBOX_API_TOKEN: ${{ secrets.ODE_MAPBOX_API_TOKEN }}
          DATABASE_URL: ${{ secrets.ODC_DATABASE_URL }}

  run_tests_gebco-bathymetry-ipynb:
    needs: build
    runs-on: ubuntu-latest
    container:
      image: oceandata.azurecr.io/odc-example-notebooks-testrunner:latest
      credentials:
        username: ${{ secrets.ACR_USERNAME }}
        password: ${{ secrets.ACR_PASSWORD }}

    steps:
      - name: List nox sessions
        run: nox -l -f /src/noxfile.py
      - name: Run tests for gebco-bathymetry-ipynb
        run:
          nox -s "test_notebook-3.9(notebook_file='/src/data/GEBCO Bathymetry/GEBCO Bathymetry.ipynb')" -f /src/noxfile.py
        env:
          ODE_CONNECTION_STR: ${{ secrets.ODE_CONNECTION_STR }}
          ODE_MAPBOX_API_TOKEN: ${{ secrets.ODE_MAPBOX_API_TOKEN }}
          DATABASE_URL: ${{ secrets.ODC_DATABASE_URL }}

  run_tests_tutorial-3-hourly-ship-emissions-ipynb:
    needs: build
    runs-on: ubuntu-latest
    container:
      image: oceandata.azurecr.io/odc-example-notebooks-testrunner:latest
      credentials:
        username: ${{ secrets.ACR_USERNAME }}
        password: ${{ secrets.ACR_PASSWORD }}

    steps:
      - name: List nox sessions
        run: nox -l -f /src/noxfile.py
      - name: Run tests for tutorial-3-hourly-ship-emissions-ipynb
        run:
          nox -s "test_notebook-3.9(notebook_file='/src/data/VesselEmissions/Tutorial 3 - Hourly Ship Emissions.ipynb')" -f /src/noxfile.py
        env:
          ODE_CONNECTION_STR: ${{ secrets.ODE_CONNECTION_STR }}
          ODE_MAPBOX_API_TOKEN: ${{ secrets.ODE_MAPBOX_API_TOKEN }}
          DATABASE_URL: ${{ secrets.ODC_DATABASE_URL }}

  run_tests_tutorial-4-green-corridor-emissions-ipynb:
    needs: build
    runs-on: ubuntu-latest
    container:
      image: oceandata.azurecr.io/odc-example-notebooks-testrunner:latest
      credentials:
        username: ${{ secrets.ACR_USERNAME }}
        password: ${{ secrets.ACR_PASSWORD }}

    steps:
      - name: List nox sessions
        run: nox -l -f /src/noxfile.py
      - name: Run tests for tutorial-4-green-corridor-emissions-ipynb
        run:
          nox -s "test_notebook-3.9(notebook_file='/src/data/VesselEmissions/Tutorial 4 - Green Corridor Emissions.ipynb')" -f /src/noxfile.py
        env:
          ODE_CONNECTION_STR: ${{ secrets.ODE_CONNECTION_STR }}
          ODE_MAPBOX_API_TOKEN: ${{ secrets.ODE_MAPBOX_API_TOKEN }}
          DATABASE_URL: ${{ secrets.ODC_DATABASE_URL }}

  run_tests_tutorial-1-gridded-emissions-data-ipynb:
    needs: build
    runs-on: ubuntu-latest
    container:
      image: oceandata.azurecr.io/odc-example-notebooks-testrunner:latest
      credentials:
        username: ${{ secrets.ACR_USERNAME }}
        password: ${{ secrets.ACR_PASSWORD }}

    steps:
      - name: List nox sessions
        run: nox -l -f /src/noxfile.py
      - name: Run tests for tutorial-1-gridded-emissions-data-ipynb
        run:
          nox -s "test_notebook-3.9(notebook_file='/src/data/VesselEmissions/Tutorial 1 - Gridded Emissions Data.ipynb')" -f /src/noxfile.py
        env:
          ODE_CONNECTION_STR: ${{ secrets.ODE_CONNECTION_STR }}
          ODE_MAPBOX_API_TOKEN: ${{ secrets.ODE_MAPBOX_API_TOKEN }}
          DATABASE_URL: ${{ secrets.ODC_DATABASE_URL }}

  run_tests_tutorial-2-voyage-emissions-data-ipynb:
    needs: build
    runs-on: ubuntu-latest
    container:
      image: oceandata.azurecr.io/odc-example-notebooks-testrunner:latest
      credentials:
        username: ${{ secrets.ACR_USERNAME }}
        password: ${{ secrets.ACR_PASSWORD }}

    steps:
      - name: List nox sessions
        run: nox -l -f /src/noxfile.py
      - name: Run tests for tutorial-2-voyage-emissions-data-ipynb
        run:
          nox -s "test_notebook-3.9(notebook_file='/src/data/VesselEmissions/Tutorial 2 - Voyage Emissions Data.ipynb')" -f /src/noxfile.py
        env:
          ODE_CONNECTION_STR: ${{ secrets.ODE_CONNECTION_STR }}
          ODE_MAPBOX_API_TOKEN: ${{ secrets.ODE_MAPBOX_API_TOKEN }}
          DATABASE_URL: ${{ secrets.ODC_DATABASE_URL }}

  run_tests_worldoceandatabase-selector-ipynb:
    needs: build
    runs-on: ubuntu-latest
    container:
      image: oceandata.azurecr.io/odc-example-notebooks-testrunner:latest
      credentials:
        username: ${{ secrets.ACR_USERNAME }}
        password: ${{ secrets.ACR_PASSWORD }}

    steps:
      - name: List nox sessions
        run: nox -l -f /src/noxfile.py
      - name: Run tests for worldoceandatabase-selector-ipynb
        run:
          nox -s "test_notebook-3.9(notebook_file='/src/data/World Ocean Database/WorldOceanDatabase_selector.ipynb')" -f /src/noxfile.py
        env:
          ODE_CONNECTION_STR: ${{ secrets.ODE_CONNECTION_STR }}
          ODE_MAPBOX_API_TOKEN: ${{ secrets.ODE_MAPBOX_API_TOKEN }}
          DATABASE_URL: ${{ secrets.ODC_DATABASE_URL }}

  run_tests_worldoceandatabase-functions-ipynb:
    needs: build
    runs-on: ubuntu-latest
    container:
      image: oceandata.azurecr.io/odc-example-notebooks-testrunner:latest
      credentials:
        username: ${{ secrets.ACR_USERNAME }}
        password: ${{ secrets.ACR_PASSWORD }}

    steps:
      - name: List nox sessions
        run: nox -l -f /src/noxfile.py
      - name: Run tests for worldoceandatabase-functions-ipynb
        run:
          nox -s "test_notebook-3.9(notebook_file='/src/data/World Ocean Database/WorldOceanDatabase_functions.ipynb')" -f /src/noxfile.py
        env:
          ODE_CONNECTION_STR: ${{ secrets.ODE_CONNECTION_STR }}
          ODE_MAPBOX_API_TOKEN: ${{ secrets.ODE_MAPBOX_API_TOKEN }}
          DATABASE_URL: ${{ secrets.ODC_DATABASE_URL }}

  run_tests_worldoceandatabase-selector-checkpoint-ipynb:
    needs: build
    runs-on: ubuntu-latest
    container:
      image: oceandata.azurecr.io/odc-example-notebooks-testrunner:latest
      credentials:
        username: ${{ secrets.ACR_USERNAME }}
        password: ${{ secrets.ACR_PASSWORD }}

    steps:
      - name: List nox sessions
        run: nox -l -f /src/noxfile.py
      - name: Run tests for worldoceandatabase-selector-checkpoint-ipynb
        run:
          nox -s "test_notebook-3.9(notebook_file='/src/data/World Ocean Database/.ipynb_checkpoints/WorldOceanDatabase_selector-checkpoint.ipynb')" -f /src/noxfile.py
        env:
          ODE_CONNECTION_STR: ${{ secrets.ODE_CONNECTION_STR }}
          ODE_MAPBOX_API_TOKEN: ${{ secrets.ODE_MAPBOX_API_TOKEN }}
          DATABASE_URL: ${{ secrets.ODC_DATABASE_URL }}

  run_tests_worldoceanatlas-ipynb:
    needs: build
    runs-on: ubuntu-latest
    container:
      image: oceandata.azurecr.io/odc-example-notebooks-testrunner:latest
      credentials:
        username: ${{ secrets.ACR_USERNAME }}
        password: ${{ secrets.ACR_PASSWORD }}

    steps:
      - name: List nox sessions
        run: nox -l -f /src/noxfile.py
      - name: Run tests for worldoceanatlas-ipynb
        run:
          nox -s "test_notebook-3.9(notebook_file='/src/data/World Ocean Atlas/WorldOceanAtlas.ipynb')" -f /src/noxfile.py
        env:
          ODE_CONNECTION_STR: ${{ secrets.ODE_CONNECTION_STR }}
          ODE_MAPBOX_API_TOKEN: ${{ secrets.ODE_MAPBOX_API_TOKEN }}
          DATABASE_URL: ${{ secrets.ODC_DATABASE_URL }}

  run_tests_wids-crw-bleaching-ipynb:
    needs: build
    runs-on: ubuntu-latest
    container:
      image: oceandata.azurecr.io/odc-example-notebooks-testrunner:latest
      credentials:
        username: ${{ secrets.ACR_USERNAME }}
        password: ${{ secrets.ACR_PASSWORD }}

    steps:
      - name: List nox sessions
        run: nox -l -f /src/noxfile.py
      - name: Run tests for wids-crw-bleaching-ipynb
        run:
          nox -s "test_notebook-3.9(notebook_file='/src/data/NOAA Coral Reef Watch/WiDS/WiDS_CRW_bleaching.ipynb')" -f /src/noxfile.py
        env:
          ODE_CONNECTION_STR: ${{ secrets.ODE_CONNECTION_STR }}
          ODE_MAPBOX_API_TOKEN: ${{ secrets.ODE_MAPBOX_API_TOKEN }}
          DATABASE_URL: ${{ secrets.ODC_DATABASE_URL }}

  run_tests_timeseries-classification-ipynb:
    needs: build
    runs-on: ubuntu-latest
    container:
      image: oceandata.azurecr.io/odc-example-notebooks-testrunner:latest
      credentials:
        username: ${{ secrets.ACR_USERNAME }}
        password: ${{ secrets.ACR_PASSWORD }}

    steps:
      - name: List nox sessions
        run: nox -l -f /src/noxfile.py
      - name: Run tests for timeseries-classification-ipynb
        run:
          nox -s "test_notebook-3.9(notebook_file='/src/data/NOAA Coral Reef Watch/WiDS/timeseries_classification.ipynb')" -f /src/noxfile.py
        env:
          ODE_CONNECTION_STR: ${{ secrets.ODE_CONNECTION_STR }}
          ODE_MAPBOX_API_TOKEN: ${{ secrets.ODE_MAPBOX_API_TOKEN }}
          DATABASE_URL: ${{ secrets.ODC_DATABASE_URL }}

  run_tests_wids-classification-ipynb:
    needs: build
    runs-on: ubuntu-latest
    container:
      image: oceandata.azurecr.io/odc-example-notebooks-testrunner:latest
      credentials:
        username: ${{ secrets.ACR_USERNAME }}
        password: ${{ secrets.ACR_PASSWORD }}

    steps:
      - name: List nox sessions
        run: nox -l -f /src/noxfile.py
      - name: Run tests for wids-classification-ipynb
        run:
          nox -s "test_notebook-3.9(notebook_file='/src/data/NOAA Coral Reef Watch/WiDS/WiDS_classification.ipynb')" -f /src/noxfile.py
        env:
          ODE_CONNECTION_STR: ${{ secrets.ODE_CONNECTION_STR }}
          ODE_MAPBOX_API_TOKEN: ${{ secrets.ODE_MAPBOX_API_TOKEN }}
          DATABASE_URL: ${{ secrets.ODC_DATABASE_URL }}

  run_tests_wids-crw-bleaching-checkpoint-ipynb:
    needs: build
    runs-on: ubuntu-latest
    container:
      image: oceandata.azurecr.io/odc-example-notebooks-testrunner:latest
      credentials:
        username: ${{ secrets.ACR_USERNAME }}
        password: ${{ secrets.ACR_PASSWORD }}

    steps:
      - name: List nox sessions
        run: nox -l -f /src/noxfile.py
      - name: Run tests for wids-crw-bleaching-checkpoint-ipynb
        run:
          nox -s "test_notebook-3.9(notebook_file='/src/data/NOAA Coral Reef Watch/WiDS/.ipynb_checkpoints/WiDS_CRW_bleaching-checkpoint.ipynb')" -f /src/noxfile.py
        env:
          ODE_CONNECTION_STR: ${{ secrets.ODE_CONNECTION_STR }}
          ODE_MAPBOX_API_TOKEN: ${{ secrets.ODE_MAPBOX_API_TOKEN }}
          DATABASE_URL: ${{ secrets.ODC_DATABASE_URL }}

  run_tests_vesselemssions-ipynb:
    needs: build
    runs-on: ubuntu-latest
    container:
      image: oceandata.azurecr.io/odc-example-notebooks-testrunner:latest
      credentials:
        username: ${{ secrets.ACR_USERNAME }}
        password: ${{ secrets.ACR_PASSWORD }}

    steps:
      - name: List nox sessions
        run: nox -l -f /src/noxfile.py
      - name: Run tests for vesselemssions-ipynb
        run:
          nox -s "test_notebook-3.9(notebook_file='/src/data/GlobalVesselEmissions/VesselEmssions.ipynb')" -f /src/noxfile.py
        env:
          ODE_CONNECTION_STR: ${{ secrets.ODE_CONNECTION_STR }}
          ODE_MAPBOX_API_TOKEN: ${{ secrets.ODE_MAPBOX_API_TOKEN }}
          DATABASE_URL: ${{ secrets.ODC_DATABASE_URL }}

  run_tests_simulator-comparing-emissions-ipynb:
    needs: build
    runs-on: ubuntu-latest
    container:
      image: oceandata.azurecr.io/odc-example-notebooks-testrunner:latest
      credentials:
        username: ${{ secrets.ACR_USERNAME }}
        password: ${{ secrets.ACR_PASSWORD }}

    steps:
      - name: List nox sessions
        run: nox -l -f /src/noxfile.py
      - name: Run tests for simulator-comparing-emissions-ipynb
        run:
          nox -s "test_notebook-3.9(notebook_file='/src/Data Products/Simulator, Comparing Emissions.ipynb')" -f /src/noxfile.py
        env:
          ODE_CONNECTION_STR: ${{ secrets.ODE_CONNECTION_STR }}
          ODE_MAPBOX_API_TOKEN: ${{ secrets.ODE_MAPBOX_API_TOKEN }}
          DATABASE_URL: ${{ secrets.ODC_DATABASE_URL }}
